name: TEMP Update Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  update-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Update Gradle Wrapper to 8.14.2
        run: ./gradlew wrapper --gradle-version 8.14.2 --distribution-type all

      - name: Check for changes
        id: git-check
        run: |
          echo "::set-output name=changed::$(git status --porcelain)"

      - name: Commit and push wrapper update
        if: steps.git-check.outputs.changed != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gradlew gradlew.bat gradle/wrapper/gradle-wrapper.properties
          git commit -m "Update Gradle Wrapper to 8.14 via GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
