name: Update Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  update-wrapper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Generate Gradle Wrapper with version 8.14.2
      run: ./gradlew wrapper --gradle-version 8.14.2 --distribution-type all

    - name: Commit and push updated wrapper files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add gradle/wrapper/gradle-wrapper.jar gradle/wrapper/gradle-wrapper.properties gradlew gradlew.bat
        git diff --quiet && echo "No changes to commit" || (git commit -m "Update Gradle wrapper to 8.14" && git push)
